CFLAGS_KERNEL='-DTSX42 -DQNAP -DARM_RK -DNAS_VIRTUAL -DNAS_VIRTUAL_EX -DQNAP_FNOTIFY -DQNAP_SEARCH_FILENAME_CASE_INSENSITIVE -DQNAP_HAL -DSUPPORT_VAAI -DQNAP_I2C_MV9235 -DSUPPORT_FAST_BLOCK_CLONE -DSUPPORT_LOGICAL_BLOCK_4KB_FROM_NAS_GUI -DSUPPORT_CONCURRENT_TASKS -DSUPPORT_SINGLE_INIT_LOGIN -DVIRTUAL_JBOD -DSUPPORT_VOLUME_BASED -DQTS_HA -DSUPPORT_TP -DNFS_VAAI -DNFS_VAAI_V3 -DNFS_QLOG -DQNAP_NFS_FORCE_UMASK -DQNAP_SNAPSHOT -DISCSI_MULTI_INIT_ACL -DUSE_BLKDEV_READPAGES -DUSE_BLKDEV_WRITEPAGES -DKSWAPD_FIX -DQNAP_KERNEL_STORAGE_V2'

CFLAGS_MODULE='-DTSX42 -DQNAP -DARM_RK -DNAS_VIRTUAL -DNAS_VIRTUAL_EX -DQNAP_FNOTIFY -DQNAP_SEARCH_FILENAME_CASE_INSENSITIVE -DQNAP_HAL -DSUPPORT_VAAI -DQNAP_I2C_MV9235 -DSUPPORT_FAST_BLOCK_CLONE -DSUPPORT_LOGICAL_BLOCK_4KB_FROM_NAS_GUI -DSUPPORT_CONCURRENT_TASKS -DSUPPORT_SINGLE_INIT_LOGIN -DVIRTUAL_JBOD -DSUPPORT_VOLUME_BASED -DQTS_HA -DSUPPORT_TP -DNFS_VAAI -DNFS_VAAI_V3 -DNFS_QLOG -DQNAP_NFS_FORCE_UMASK -DQNAP_SNAPSHOT -DISCSI_MULTI_INIT_ACL -DUSE_BLKDEV_READPAGES -DUSE_BLKDEV_WRITEPAGES -DKSWAPD_FIX -DQNAP_KERNEL_STORAGE_V2 -DMODULE'

kernel_config_manager() {
    local config_file="$1"
    
    # 配置项矩阵（与原有flags保持风格统一）
	#rock-5c 不需要["SATA-倍增"]="CONFIG_SATA_PMP=y"
	#rock-5c 不需要["PCIe-电源节电"]="# CONFIG_PCIEASPM_DEFAULT is not set\nCONFIG_PCIEASPM_POWER_SUPERSAVE=y"
    declare -A config_matrix=(
		["PCIe-电源节电"]="# CONFIG_PCIEASPM_DEFAULT is not set\nCONFIG_PCIEASPM_POWER_SUPERSAVE=y"
        ["UHID-蓝牙遥控"]="CONFIG_UHID=m"
        ["LED-心跳包"]="CONFIG_LEDS_TRIGGER_HEARTBEAT=m"
        ["RTC"]="CONFIG_RTC_DRV_HYM8563=y\nCONFIG_RTC_DRV_RK808=y"
        ["FAN-pwm风扇"]="CONFIG_SENSORS_PWM_FAN=y"
        ["IRC-红外遥控"]="CONFIG_ROCKCHIP_REMOTECTL=y\nCONFIG_ROCKCHIP_REMOTECTL_PWM=y"
    )

    # 智能清理策略
    for key in "${!config_matrix[@]}"; do
        echo "[INFO] 处理配置组: $key"
        while read -r entry; do
            # 参数提取器（兼容QNAP风格注释）
            if [[ $entry == "#"* ]]; then
                param=$(awk '{gsub(/^# +|([ =].*)/, ""); print}' <<< "$entry")
            else
                param=$(cut -d= -f1 <<< "$entry")
            fi
            
            # 安全删除模式（保留其他配置项）
            sed -i "/^[# ]*${param}[ =]/d" "$config_file"
        done <<< $(echo -e "${config_matrix[$key]}")
    done

    # 批量写入优化（避免重复IO）
    {
        for key in "${!config_matrix[@]}"; do
            echo -e "\n# QNAP定制: $key"
            echo -e "${config_matrix[$key]}"
        done
    } >> "$config_file"

    # 依赖关系解析    
}
PATCH_FILES="0001-add-qnap-QND_FNOTIFY-QND_HAL-Kconfig.patch
			0002-fix-qnap-rockchip-pwm.patch
			0008-LINUX_COMPILE_BY-r-MT.patch
			0009-P010-P210-support.patch
			0010-add-include-dt-bindings-input-rk-ir.h.patch
			0011-add-rockchip-irc-remotectl-driver.patch
			0012-fix-qnap-rockchip-pwm-fan-v1.1.patch"
DTB_PATCH_FILES="0010-add-include-dt-bindings-input-rk-ir.h.patch"