[System Enclosure]
MODEL = TS-AI642
ADJUST_SYS_TEMP=0
ADJUST_CPU_TEMP=FORMULA:8
SMART_FAN_CPU_WARM_TEMP=70
SMART_FAN_CPU_CRIT_TEMP=75
SMART_FAN_SYS_WARM_TEMP=70
SMART_FAN_SYS_CRIT_TEMP=75
SMART_FAN_METHOD=TFAN:SW

[TFAN CPU]
TFAN_SAMPLE_TIME = 1
TFAN_LOWER_DUTY = 30
TFAN_NORMAL_DUTY = 30
TFAN_TRANSITION_DUTY = 50
TFAN_MAX_DUTY = 100
TFAN_MAX_PWM = 255
TFAN_PERIOD = 5:5:5
TFAN_N2T2M = 5:10
TFAN_M2T2N = 10:5
USING SCROLLBAR = yes
OPTIONAL MODES = yes
TFAN_NORMAL_MODE = 55:65:70
TFAN_COMP_RESET_H = 3
TFAN_BUFFER_LENGTH = 1

[TFAN SYS]
TFAN_SAMPLE_TIME = 1
TFAN_LOWER_DUTY = 30
TFAN_NORMAL_DUTY = 30
TFAN_TRANSITION_DUTY = 50
TFAN_MAX_DUTY = 100
TFAN_MAX_PWM = 255
TFAN_PERIOD = 5:5:5
TFAN_N2T2M = 2.5:5
TFAN_M2T2N = 5:2.5
TFAN_PCI_EFFECT = 10
OPTIONAL MODES = yes
USING SCROLLBAR = yes
TFAN_NORMAL_MODE = 40:45:50
TFAN_QUIET_MODE = 45:50:55
TFAN_PERFORMANCE_MODE = 35:40:45
TFAN_COMP_RESET_H = 3
TFAN_BUFFER_LENGTH = 1

[TFAN DISK]
TFAN_PERIOD = 5:5:5
TFAN_N2T2M = 10:15
TFAN_M2T2N = 15:10
TFAN_NORMAL_MODE = 47:52
TFAN_COMP_RESET_H = 3
TFAN_BUFFER_LENGTH = 1
TFAN_PRE_INC = 60

[SHUTDOWN TEMP]
CPU_TEMP = 80
SYS_TEMP = 80
DISK_TEMP = 70

