#!/usr/bin/env bash
UBOOT_CONFIG="roc-rk3588s-pc-rk3588s"
DTS_FILES="rk3588s-roc-pc"
declare -g -A KERNEL_VERSIONS=(
    # [510]='(
        # #[part0]="https://sourceforge.net/projects/qosgpl/files/QNAP%20NAS%20GPL%20Source/QTS%205.1.0/QTS_Kernel_5.1.0.20230808.tar.gz.0/download"
        # #[part1]="https://sourceforge.net/projects/qosgpl/files/QNAP%20NAS%20GPL%20Source/QTS%205.1.0/QTS_Kernel_5.1.0.20230808.tar.gz.1/download"
        # [part0]="http://10.10.10.5/qnap-kernel/QTS_Kernel_5.1.0.20230808.tar.gz.0"
        # [part1]="http://10.10.10.5/qnap-kernel/QTS_Kernel_5.1.0.20230808.tar.gz.1"
		# [part0_md5]="4bbfe010406d0f1ecc16615ee26d8cdc"
		# [part1_md5]="8633469c2d6a8f04ded999bab579c579"
        # [dir]="GPL_QTS"      # 解压后的根目录名称
        # [parts]="2"           # 分卷总数
        # [tar_opts]="z"        # tar解压参数：z=用gzip解压
        # [MIN_VER]="510"       # 最低兼容版本 (QTS 5.1.0 → 0x01FE → 510)
        # [MAX_VER]="520"       # 最高兼容版本 (QTS 5.2.0 → 0x0208 → 520)
        # [dtb_offset]="$((0x219800))"    # DTB起始地址 (0x00219800 00 21 98 00)
        # [kernel_offset]="$((0x241800))"  # 内核起始地址 (0x00241800 00 24 18 00)
        # [sectors]="$((0x32000))"        # 分配扇区数 (0x32000 × 512 = 104MB)
    # )'

    [520]='(
        [part0]="https://sourceforge.net/projects/qosgpl/files/QNAP%20NAS%20GPL%20Source/QTS%205.2.0/QTS_Kernel_5.2.0.20240910.0.tar.gz/download"
        [part1]="https://sourceforge.net/projects/qosgpl/files/QNAP%20NAS%20GPL%20Source/QTS%205.2.0/QTS_Kernel_5.2.0.20240910.1.tar.gz/download"
        # [part0]="http://10.10.10.5/qnap-kernel/QTS_Kernel_5.2.0.20240910.0.tar.gz"
        # [part1]="http://10.10.10.5/qnap-kernel/QTS_Kernel_5.2.0.20240910.1.tar.gz"
		[part0_md5]="4c39f8ca025076e332879f1cabbd2ca0"
		[part1_md5]="3f4ab68cced5a3c8fa9bddc27e66eb96"
        [dir]="GPL_QTS"
        [parts]="2"
        [tar_opts]="z"
        [MIN_VER]="521"       # QTS 5.2.1 → 0x0209 → 521
        [MAX_VER]="522"       # QTS 5.2.2 → 0x020a
        [dtb_offset]="$((0x21B800))"    # DTB起始地址 (0x0021b800 00 21 b8 00)
        [kernel_offset]="$((0x273800))" # 内核起始地址 (0x00273800 00 27 38 00)
        [sectors]="$((0x32000))"        # 分区大小保持104MB
    )'

    [523]='(
        [part0]="https://sourceforge.net/projects/qosgpl/files/QNAP%20NAS%20GPL%20Source/QTS%205.2.3/QTS_Kernel_5.2.3.20250218.0.tar.gz/download"
        [part1]="https://phoenixnap.dl.sourceforge.net/project/qosgpl/QNAP%20NAS%20GPL%20Source/QTS%205.2.3/QTS_Kernel_5.2.3.20250218.1.tar.gz?viasf=1"
        # [part1]="https://sourceforge.net/projects/qosgpl/files/QNAP%20NAS%20GPL%20Source/QTS%205.2.3/QTS_Kernel_5.2.3.20250218.1.tar.gz/download"
        # [part0]="http://10.10.10.5/qnap-kernel/QTS_Kernel_5.2.3.20250218.0.tar.gz"
        # [part1]="http://10.10.10.5/qnap-kernel/QTS_Kernel_5.2.3.20250218.1.tar.gz"
		[part0_md5]="27c37b7f92578d3ce8991e0b934368f2"
		[part1_md5]="25f9930db5d2683b79dfb711e8e27fa5"
        [dir]="GPL_QTS"
        [parts]="2"
        [tar_opts]="z"
        [MIN_VER]="523"     # QTS 5.2.3 → 0x020b
        [MAX_VER]="630"     # QTS 6.3.0 → 0x0276
        [dtb_offset]="$((0x21D800))"    # DTB起始地址
        [kernel_offset]="$((0x2A5800))" # 内核起始地址
        [sectors]="$((0x32000))"        # 分区大小保持104MB
    )'
)
